spring:
  profiles:
    active: default
---
spring:
  profiles: default
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/StadnykYura/spring-cloud-test.git
          searchPaths: /spring-cloud-microservices-poc
          # username: <PLEASE UPDATE>
          # password: <PLEASE UPDATE>
          clone-on-start: true
      discovery:
        enabled: true

server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/StadnykYura/spring-cloud-test.git
          searchPaths: /spring-cloud-microservices-poc
          # username: <PLEASE UPDATE>
          # password: <PLEASE UPDATE>
server:
  port: 8888

eureka:
  instance:
    hostname: configuration-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
