spring:
  profiles:
    active: default
---
spring:
  profiles: default

zuul:
  routes:
    task-service:
      path: /task-service/**
      serviceId: task-service
    user-service:
      path: /user-service/**
      serviceId: user-service

user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    ConnectTimeout: 40000
    ReadTimeout: 40000
    maxAutoRetries: 2
    MaxAutoRetriesNextServer: 2
    eureka:
      enabled: false
    listOfServers: http://localhost:8081

task-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    ConnectTimeout: 40000
    ReadTimeout: 40000
    maxAutoRetries: 2
    MaxAutoRetriesNextServer: 2
    eureka:
      enabled: false
    listOfServers:  http://localhost:8083, http://localhost:8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  application:
    name: gateway-service
  cloud:
    config:
      uri: http://configuration-service:8888
      discovery:
        enabled: true
server:
  port: 9090

zuul:
  routes:
    task-service:
      path: /task-service/**
      serviceId: task-service
    user-service:
      path: /user-service/**
      serviceId: user-service

user-service:
  ribbon:
    ConnectTimeout: 40000
    ReadTimeout: 40000
    maxAutoRetries: 2
    MaxAutoRetriesNextServer: 2
    eureka:
      enabled: true

task-service:
  ribbon:
    ConnectTimeout: 40000
    ReadTimeout: 40000
    maxAutoRetries: 2
    MaxAutoRetriesNextServer: 2
    eureka:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/